# Generated by Django 3.0 on 2019-12-13 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('totalTimeInDays', models.IntegerField()),
                ('seedsCostperSqFeet', models.IntegerField()),
                ('fertilizerCostPerSqFeet', models.IntegerField()),
                ('landPreperationTimeInDays', models.IntegerField()),
                ('SeedingTimeInDays', models.IntegerField()),
                ('transplantationTimeInDays', models.IntegerField()),
                ('irrigationTimeInDays', models.IntegerField()),
                ('weedingTimeInDays', models.IntegerField()),
                ('fertilizingTimeInDays', models.IntegerField()),
                ('harvestingTimeInDays', models.IntegerField()),
                ('waterRequirementInMM', models.IntegerField()),
                ('minRainfallDuringIrrigationInMM', models.IntegerField()),
                ('maxRainfallDuringIrrigationInMM', models.IntegerField()),
                ('minTempInDays', models.IntegerField()),
                ('maxTempInDays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmersQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('areaInSquarefeets', models.IntegerField()),
                ('budgetInRupees', models.IntegerField()),
                ('stayStrict', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicApp.Crop')),
            ],
        ),
    ]
