# Generated by Django 3.0 on 2019-12-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0002_auto_20191213_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='SeedingTimeInDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='fertilizerCostPerSqFeet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='fertilizingTimeInDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='harvestingTimeInDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='irrigationTimeInDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='landPreperationTimeInDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='maxRainfallDuringIrrigationInMM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='maxTempInDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='maxwaterRequirementInMM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='minRainfallDuringIrrigationInMM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='minTempInDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='seedsCostperSqFeet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='totalTimeInDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='transplantationTimeInDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='weedingTimeInDays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
